#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

./configure \
    --prefix=/usr \
    --with-lib-path=/usr/lib:/usr/local/lib \
    --build=i686-pc-linux-musl \
    --host=i686-pc-linux-musl \
    --enable-targets=x86_64-pep \
    --enable-64-bit-bfd \
    --enable-gold \
    --enable-lto \
    --enable-ld=default \
    --enable-plugins \
    --disable-multilib \
    --disable-werror \
    --disable-gdb \
    --disable-nls \
    --disable-readline \
    --disable-gprof \
    --with-mmap \
    --with-system-zlib

make configure-host
make tooldir=/usr
make prefix="$1/usr" tooldir="$1/usr" install
